/********************************************************************
* TaskDataDictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TaskDataDictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTaskDataDictionary();
extern void G__cpp_setup_inheritanceTaskDataDictionary();
extern void G__cpp_setup_typetableTaskDataDictionary();
extern void G__cpp_setup_memvarTaskDataDictionary();
extern void G__cpp_setup_globalTaskDataDictionary();
extern void G__cpp_setup_memfuncTaskDataDictionary();
extern void G__cpp_setup_funcTaskDataDictionary();
extern void G__set_cpp_environmentTaskDataDictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TaskData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TaskDataDictionaryLN_TClass;
extern G__linked_taginfo G__TaskDataDictionaryLN_TBuffer;
extern G__linked_taginfo G__TaskDataDictionaryLN_TMemberInspector;
extern G__linked_taginfo G__TaskDataDictionaryLN_TObject;
extern G__linked_taginfo G__TaskDataDictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TaskDataDictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TaskDataDictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TaskDataDictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TaskDataDictionaryLN_Event;
extern G__linked_taginfo G__TaskDataDictionaryLN_Track;

/* STUB derived class for protected member access */
